In [26]:
import numpy as np
c = np.array([2, -3, 4])
A = np.array([[1, 1, 1], [2, 1, 0], [0, 3, 1]])
b = np.array([3, 5, 4])

In [29]:
m, n_old = A.shape
n = n_old + m
# Converting to standard form Ax = b
A = np.hstack((A, np.eye(A.shape[0])))
c = np.hstack((c, np.zeros(A.shape[0])))
# Minimising c
c = -c

# making b positive
for i in range(m):
    if(b[i] < 0):
        b[i] = -b[i]
        A[i,:] = -A[i,:]

# Phase1
# Ax + Iy = b
c_phase1 = np.concatenate((np.zeros(n), np.ones(m)))
A_phase1 = np.hstack((A, np.eye(m)))
basis_indices = np.arange(n, n+m)

# Constructing initial tableau
T = np.zeros((m+1, n+m+1))
# T[1:, 1:] = A
# T[1:,0] = b
# T[0, 1:] = c_phase1 - np.ones(m).T @ A
# T[0,0] = -np.ones(m) @ b
T[:-1, :-1] = A_phase1
T[0:-1:,-1] = b
T[-1, :-1] = c_phase1 - np.ones(m).T @ A_phase1
T[-1,-1] = -np.ones(m) @ b


In [30]:
T

array([[  1.,   1.,   1.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,
          0.,   3.],
       [  2.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,
          0.,   5.],
       [  0.,   3.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,
          1.,   4.],
       [ -3.,  -5.,  -2.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,   0.,   0.,
          0., -12.]])

In [31]:
b

array([3, 5, 4])

In [7]:
A = np.ones((10,3))

In [18]:
b @ A

array([10., 10., 10.])

In [19]:
b@b

10.0

In [23]:
a = np.array([1,2,3])

In [24]:
c = np.array([3,4,0])

In [25]:
a/c

/tmp/ipykernel_750889/749814572.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/c


array([0.33333333, 0.5       ,        inf])